### ISSUE TITLE
the number of parameters dose not fits 

### ISSUE THREAD

**Issue by yueshiyi** [Lyken17/SparseNet#2]
There is a small discrepancy in the number of parameters between the paper and this version of code.
The number of parameters of the sparsenet-40-24  is 0.73m according to the code, and it should be 0.76m according to your paper. Sorry, I don’t known what’s going wrong, can you help me?

**Comment by Lyken17** [comment]
Thanks for you interest in our work. 

The small discrepancy is caused by my mistake in source code 

In line ~161
```python
         if fetch in ["linear", "dense"]:
             nChannels = 2 * growthRate
         elif fetch in ["exp", "sparse"]:
             nChannels = growthRate
```

This is one of our experimental settings, to explore how the `initial block` size affects model performance. In final release version, please change to 
 ```python
             nChannels = 2 * growthRate
```

Then the parameters will be exactly same as listed in the paper.

**Comment by Lyken17** [comment]
I will soon fix the mistake in next update, together with imagenet pretrained models.

**Comment by Lyken17** [comment]
Closed for no update after a long time. Feel free to reopen it if necessary.
